import Button from '@mui/material/Button';
import TextField from '@mui/material/TextField';
import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import { atom, useRecoilState, useSetRecoilState } from 'recoil';
import styles from '../styles/Home.module.css';

export const getStaticProps: GetStaticProps = async (context) => {
  return {
    props: {},
  };
};

type Domain = {
  address: string[];
};

const domainAtom = atom<string[]>({
  key: 'domainIP',
  default: [],
});

const targetDomainAtom = atom<string>({
  key: 'targetDomain',
  default: '',
});

const Home: NextPage = () => {
  const [targetDomain, setTargetDomain] =
    useRecoilState<string>(targetDomainAtom);
  const [domainIP, setDomainIP] = useRecoilState<Domain['address']>(domainAtom);

  const getDomainIP = async (domain: string): Promise<Domain['address']> => {
    const getDomainIp = await fetch(`http://localhost:8080/domain/${domain}`);
    const ip: Domain = await getDomainIp.json();
    return ip.address;
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <TextField
          id="outlined-basic"
          label="Outlined"
          variant="outlined"
          onChange={(e) => setTargetDomain(e.target.value)}
        />
        <Button
          onClick={async () => {
            await getDomainIP(targetDomain)
              .then((res) => setDomainIP(res))
              .catch((err) => console.log(err));
          }}
          variant="text"
        >
          Search for Domain IPv4 address
        </Button>

        {domainIP && (
          <h1 className={styles.title}>IP address is: {domainIP[0]}</h1>
        )}
      </main>
    </div>
  );
};

export default Home;
